const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.Browser,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Arr.Acts.Pop,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Arr.Exps.Back,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetVisible
	];
};
self.C3_JsPropNameTable = [
	{Mouse: 0},
	{Touch: 0},
	{Audio: 0},
	{Array: 0},
	{kapak: 0},
	{Sine: 0},
	{btn_play: 0},
	{btn_info: 0},
	{btn_emgecen: 0},
	{btn_kaynakca: 0},
	{btn_home: 0},
	{btn_ekranboyut: 0},
	{btn_sesac: 0},
	{btn_seskapat: 0},
	{oyun_arkplan: 0},
	{tebrik_arkplan: 0},
	{btn_tekraroyna: 0},
	{soru_cerceve: 0},
	{Tween: 0},
	{info: 0},
	{meb_logo: 0},
	{durum: 0},
	{soru: 0},
	{correct: 0},
	{sure_halka: 0},
	{Timer: 0},
	{sure_text: 0},
	{"1no": 0},
	{tik: 0},
	{"2no": 0},
	{"3no": 0},
	{tabrikcerceve: 0},
	{wrong: 0},
	{Browser: 0},
	{Array2: 0},
	{dogru: 0},
	{yanlis: 0},
	{Sprite: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{btns: 0},
	{hand: 0},
	{sorular: 0},
	{infopage: 0},
	{posx: 0},
	{posy: 0},
	{secenekler: 0},
	{tiklama: 0},
	{cvpSayisi: 0},
	{dogrusayisi: 0},
	{yanlissayisi: 0},
	{sure_deg: 0}
];

self.InstanceType = {
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	kapak: class extends self.ISpriteInstance {},
	btn_play: class extends self.ISpriteInstance {},
	btn_info: class extends self.ISpriteInstance {},
	btn_emgecen: class extends self.ISpriteInstance {},
	btn_kaynakca: class extends self.ISpriteInstance {},
	btn_home: class extends self.ISpriteInstance {},
	btn_ekranboyut: class extends self.ISpriteInstance {},
	btn_sesac: class extends self.ISpriteInstance {},
	btn_seskapat: class extends self.ISpriteInstance {},
	oyun_arkplan: class extends self.ISpriteInstance {},
	tebrik_arkplan: class extends self.ISpriteInstance {},
	btn_tekraroyna: class extends self.ISpriteInstance {},
	soru_cerceve: class extends self.ISpriteInstance {},
	info: class extends self.ISpriteInstance {},
	meb_logo: class extends self.ISpriteInstance {},
	soru: class extends self.ISpriteInstance {},
	correct: class extends self.ISpriteInstance {},
	sure_halka: class extends self.ISpriteInstance {},
	sure_text: class extends self.ITextInstance {},
	_1no: class extends self.ITextInstance {},
	tik: class extends self.ISpriteInstance {},
	_2no: class extends self.ITextInstance {},
	_3no: class extends self.ITextInstance {},
	tabrikcerceve: class extends self.ISpriteInstance {},
	wrong: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	Array2: class extends self.IArrayInstance {},
	dogru: class extends self.ITextInstance {},
	yanlis: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	btns: class extends self.ISpriteInstance {},
	hand: class extends self.ISpriteInstance {},
	sorular: class extends self.ISpriteInstance {}
}